name: Workflow lors d'un push
on: push
jobs:
  mon_job:
    name: Build teste et run mon application
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code
        uses: actions/checkout@v4
      - name: cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          # voir aussi : actions/setup-node
      - name: installation des node_modules
        run: npm ci
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: start
        run: npm run start
    

  